a=int(input("enter value of a:"))
b=int(input("enter value of b:"))
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplicaton:",a*b)
print("division:",a/b)
print("floor division:",a//b)
print("modus:",a%b)
print("power:",a**b)
